services:
  api:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    container_name: gin-server
    environment:
      - GIN_MODE=release
    ports:
      - 3001:3001
    volumes:
      - "..:/app"
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
volumes:
  mongo-data: